version: '3.7'

services:
  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: atomic-sensors
    ports:
      - "27017:27017"
    networks:
      - net
  
  queue:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-queue
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./Queue/config:/mosquitto/config
      - ./Queue/log:/mosquitto/log
      - ./Queue/data:/mosquitto/data
    networks:
      - net

  backend:
    build: backend
    container_name: backend
    environment:
      ConnectionStrings__MongoDB: mongodb://root:root@mongodb:27017 
      MQTT__Port: 1883
      MQTT__Host: queue
      ASPNETCORE_URLS: http://+:5000
    ports:
      - "5000:5000"
    networks: 
      - net 
    depends_on: 
      - database 
      - queue

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '4200:4200'
    environment:
      - PORT=4200
    networks:
      - net


networks:
  net:
    driver: bridge
    